### ISSUE TITLE
Dlaczego metody do obslugi akcji w controllerach nazywaja sie test?

### ISSUE THREAD

**Issue by nexik** [Ferror/Landingi#6]
Domyslnie wedlug przyjetych standardów, raczej powinny sie nazywac indexAction()

**Comment by Ferror** [comment]
Dla kazdego kontrolera powinna istniec funkcja indexAction, czy tylko dla tego, ktory wywolywany jest jako pierwszy?

**Comment by nexik** [comment]
jezeli controller ma jedna metode to raczej indexAction jezeli np mamy controller ArticleController to czesto (przy aplikacjach typu CRUD - Create Read Update Delete) mamy metody:

showAction()
addAction()
updateAction()
deleteAction()
